### ISSUE TITLE
 EDITOR="vi --wait"  bin/rails credentials:edit --environment=production

### ISSUE THREAD

**Issue by Aro7979** [Aro7979/Texnika#1]
Добрый день. При запуске EDITOR="vi --wait"  bin/rails credentials:edit --environment=production
получаю ошибку:/home/deploy/.rbenv/versions/3.0.3/lib/ruby/3.0.0/debug.rb:6:in `<main>': undefined method `>' for nil:NilClass (NoMethodError)
	from /home/deploy/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /home/deploy/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /home/deploy/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /home/deploy/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/runtime.rb:55:in `each'
	from /home/deploy/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/runtime.rb:55:in `block in require'
	from /home/deploy/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/runtime.rb:44:in `each'
	from /home/deploy/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/runtime.rb:44:in `require'
	from /home/deploy/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler.rb:175:in `require'
	from /home/deploy/www/config/application.rb:7:in `<main>'
	from /home/deploy/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /home/deploy/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /home/deploy/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.6/lib/rails/command/actions.rb:22:in `require_application!'
	from /home/deploy/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.6/lib/rails/commands/credentials/credentials_command.rb:30:in `edit'
	from /home/deploy/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from /home/deploy/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/deploy/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from /home/deploy/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.6/lib/rails/command/base.rb:87:in `perform'
	from /home/deploy/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.6/lib/rails/command.rb:48:in `invoke'
	from /home/deploy/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.6/lib/rails/commands.rb:18:in `<main>'
	from /home/deploy/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /home/deploy/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from bin/rails:4:in `<main>'
как мне исправить ошибку?

**Comment by Aro7979** [comment]
Я нашел ответ, не правильно было изьято secret_master_key
